-- =============================================================================
-- feature_store.sql — Part 5: AI/ML Readiness
-- Churn prediction feature store for AWS SageMaker
-- =============================================================================
--
-- TARGET VARIABLE (not stored here, computed at training time):
--   churned = 1 if contractor placed zero completed orders in the 90 days
--             following the snapshot_date, 0 otherwise.
--
-- GRAIN: one row per (contractor_id, snapshot_date)
--   snapshot_date is a point-in-time date; features are computed as of that date.
--   This enables time-travel training (no leakage) and rolling daily/weekly
--   feature refresh for inference.
--
-- WHY POINT-IN-TIME SNAPSHOTS?
--   SageMaker Feature Store supports offline (S3-backed) and online (low-latency)
--   feature groups. The offline store is append-only with an event_time column,
--   which is exactly our snapshot_date. Training joins pull the latest feature
--   row whose snapshot_date <= training label date.
-- =============================================================================

CREATE TABLE curated.contractor_churn_features AS
WITH
-- ============================================================
-- Anchor: one row per contractor per snapshot date
-- In production, this is generated by a daily scheduler.
-- ============================================================
snapshots AS (

    SELECT
        c.contractor_id,
        -- In batch feature generation, snapshot_date is passed in as a parameter.
        -- Here we compute features as of the last date in the dataset.
        '2024-06-30'::date       AS snapshot_date
    FROM   curated.dim_contractors c

),

-- ============================================================
-- Feature group A: Recency, Frequency, Monetary (RFM)
-- All metrics are computed as of snapshot_date.
-- ============================================================
rfm AS (

    SELECT
        o.contractor_id,
        s.snapshot_date,

        -- Recency: days since most recent completed order
        datediff('day', max(o.created_date), s.snapshot_date)          AS days_since_last_order,

        -- Frequency: completed order count in trailing windows
        sum(case when o.created_date >= dateadd('day', -30,  s.snapshot_date)
                  and o.is_completed then 1 else 0 end)                 AS orders_l30d,
        sum(case when o.created_date >= dateadd('day', -60,  s.snapshot_date)
                  and o.is_completed then 1 else 0 end)                 AS orders_l60d,
        sum(case when o.created_date >= dateadd('day', -90,  s.snapshot_date)
                  and o.is_completed then 1 else 0 end)                 AS orders_l90d,
        sum(case when o.is_completed then 1 else 0 end)                 AS orders_lifetime,

        -- Monetary: spend in trailing windows
        sum(case when o.created_date >= dateadd('day', -30,  s.snapshot_date)
                  and o.is_completed then o.order_total_amount else 0 end) AS spend_l30d,
        sum(case when o.created_date >= dateadd('day', -90,  s.snapshot_date)
                  and o.is_completed then o.order_total_amount else 0 end) AS spend_l90d,
        sum(case when o.is_completed then o.order_total_amount else 0 end) AS spend_lifetime,

        -- Average order value (lifetime)
        avg(case when o.is_completed then o.order_total_amount end)     AS avg_order_value_lifetime,

        -- Cancellation behaviour
        sum(case when o.is_cancelled then 1 else 0 end)                 AS cancelled_orders_lifetime,
        round(
            100.0 * sum(case when o.is_cancelled then 1 else 0 end)
                  / nullif(count(*), 0),
            2
        )                                                                AS cancellation_rate_pct

    FROM   snapshots                s
    JOIN   curated.fct_orders       o ON s.contractor_id = o.contractor_id
                                      AND o.created_date <= s.snapshot_date
    GROUP  BY o.contractor_id, s.snapshot_date

),

-- ============================================================
-- Feature group B: Order trend (is the contractor ramping up
-- or winding down?)
-- ============================================================
trend AS (

    SELECT
        o.contractor_id,
        s.snapshot_date,

        -- MoM order count change (last month vs. month before)
        sum(case when o.created_date >= dateadd('day', -30, s.snapshot_date)
                  and o.is_completed then 1 else 0 end)
        - sum(case when o.created_date between dateadd('day', -60, s.snapshot_date)
                                          and dateadd('day', -31, s.snapshot_date)
                  and o.is_completed then 1 else 0 end)                AS order_count_mom_delta,

        -- MoM spend change
        sum(case when o.created_date >= dateadd('day', -30, s.snapshot_date)
                  and o.is_completed then o.order_total_amount else 0 end)
        - sum(case when o.created_date between dateadd('day', -60, s.snapshot_date)
                                          and dateadd('day', -31, s.snapshot_date)
                  and o.is_completed then o.order_total_amount else 0 end) AS spend_mom_delta

    FROM   snapshots                s
    JOIN   curated.fct_orders       o ON s.contractor_id = o.contractor_id
                                      AND o.created_date <= s.snapshot_date
    GROUP  BY o.contractor_id, s.snapshot_date

),

-- ============================================================
-- Feature group C: Contractor profile (static / slow-changing)
-- ============================================================
profile AS (

    SELECT
        c.contractor_id,
        c.plan_type,
        c.plan_tier,
        c.region,
        c.days_on_platform,
        -- Months on platform (coarser, potentially more stable than days)
        floor(c.days_on_platform / 30.0)    AS months_on_platform

    FROM   curated.dim_contractors c

),

-- ============================================================
-- Feature group D: Ordering regularity / consistency
-- ============================================================
regularity AS (

    SELECT
        o.contractor_id,
        s.snapshot_date,
        -- Average days between orders (proxy for expected purchase cadence)
        avg(datediff('day', prev_date, o.created_date))    AS avg_days_between_orders,
        -- Stddev of inter-order intervals (high = irregular/sporadic)
        stddev(datediff('day', prev_date, o.created_date)) AS stddev_days_between_orders
    FROM (
        SELECT
            contractor_id,
            created_date,
            lag(created_date) OVER (
                PARTITION BY contractor_id
                ORDER BY created_date
            ) AS prev_date
        FROM   curated.fct_orders
        WHERE  is_completed = true
    ) o
    JOIN snapshots s ON o.contractor_id = s.contractor_id
                     AND o.created_date <= s.snapshot_date
    WHERE  o.prev_date IS NOT NULL
    GROUP  BY o.contractor_id, s.snapshot_date

)

-- ============================================================
-- Final feature table assembly
-- ============================================================
SELECT
    -- SageMaker Feature Store required columns
    s.contractor_id                                             AS record_id,
    s.snapshot_date                                             AS event_time,   -- point-in-time key

    -- Profile features (C)
    p.plan_type,
    p.plan_tier,
    p.region,
    p.days_on_platform,
    p.months_on_platform,

    -- RFM features (A)
    coalesce(r.days_since_last_order,       999)               AS days_since_last_order,
    coalesce(r.orders_l30d,                 0)                 AS orders_l30d,
    coalesce(r.orders_l60d,                 0)                 AS orders_l60d,
    coalesce(r.orders_l90d,                 0)                 AS orders_l90d,
    coalesce(r.orders_lifetime,             0)                 AS orders_lifetime,
    coalesce(r.spend_l30d,                  0)                 AS spend_l30d,
    coalesce(r.spend_l90d,                  0)                 AS spend_l90d,
    coalesce(r.spend_lifetime,              0)                 AS spend_lifetime,
    r.avg_order_value_lifetime,
    coalesce(r.cancelled_orders_lifetime,   0)                 AS cancelled_orders_lifetime,
    coalesce(r.cancellation_rate_pct,       0)                 AS cancellation_rate_pct,

    -- Trend features (B)
    coalesce(t.order_count_mom_delta,       0)                 AS order_count_mom_delta,
    coalesce(t.spend_mom_delta,             0)                 AS spend_mom_delta,

    -- Regularity features (D)
    reg.avg_days_between_orders,
    reg.stddev_days_between_orders,

    -- Derived ratios useful for tree-based models
    case
        when coalesce(r.orders_lifetime, 0) = 0 then null
        else round(r.orders_l30d * 1.0 / r.orders_lifetime, 4)
    end                                                        AS orders_l30d_share,

    case
        when coalesce(r.spend_lifetime, 0) = 0 then null
        else round(r.spend_l90d / r.spend_lifetime, 4)
    end                                                        AS spend_l90d_share

FROM   snapshots            s
LEFT JOIN rfm               r   ON s.contractor_id = r.contractor_id
                                AND s.snapshot_date  = r.snapshot_date
LEFT JOIN trend             t   ON s.contractor_id = t.contractor_id
                                AND s.snapshot_date  = t.snapshot_date
LEFT JOIN profile           p   ON s.contractor_id = p.contractor_id
LEFT JOIN regularity        reg ON s.contractor_id = reg.contractor_id
                                AND s.snapshot_date  = reg.snapshot_date
;

-- =============================================================================
-- FEATURE FRESHNESS STRATEGY
-- =============================================================================
-- 1. Daily batch job (Glue or dbt run): regenerates snapshot rows for current_date
--    and appends to the offline store. SageMaker Feature Store ingests from S3.
-- 2. Online store: enabled on the Feature Group for real-time inference (low-latency
--    PutRecord API called after each order is placed / status changes).
-- 3. Point-in-time correctness: training joins use
--    "latest feature row where event_time <= label_date" to prevent leakage.
-- 4. Schema evolution: additive columns only — SageMaker Feature Store does not
--    support column deletion. Deprecated columns are null-filled.
-- =============================================================================
